### ISSUE TITLE
Can't switch screens after event added

### ISSUE THREAD

**Issue by computerquest** [computerquest/Time#24]
After adding an event you can no longer swipe to the TaskManagerActivity. Debgugging has shown that they onStart method is called but the onCreate method of the other activity is never used. There is no error in the console and the app continues to run.

**Comment by computerquest** [comment]
The whole interface freezes.

**Comment by jpaav** [comment]
A stack trace describes this error as follows: "Parcelable encountered IOException writing serializable object EventHandler" Caused by: "Android.TextView" TextView is non serializable and causes this exception. I have no idea why it only occurs after adding an event
